apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  selector:
    app: {{ .Release.Name }}-fastapi
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}